### Goldsmiths University of London
### Author....: Carlos Manuel de Oliveira Alves
### Student...: cdeol003
### Created...: 08/02/2023
### FYP.......: NeuroCredit

In [1]:
# Importing the pandas library to read the data
import pandas as pd

In [2]:
# Reading the data with credit loans data
data = pd.read_csv('data.csv')

In [4]:
# Printing the first 5 rows of the data
data.head().T

,0,1,2,3,4
credit_history,Fair,Good,Good,Good,Excellent
income,34084,20938,20734,14186,46693
employment_status,Employed,Self-Employed,Employed,Unemployed,Unemployed
collateral,Land,Car,Land,Car,Land
assets_value,39837,33241,12926,16586,30771
debt_to_income_ratio,76,53,52,67,66
payment_history,Excellent,Poor,Excellent,Poor,Excellent
length_of_credit_history,84,59,84,92,39
number_of_credit_inquiries,5,3,1,5,1
number_of_credit_accounts,0,3,1,5,2
number_of_credit_accounts_opened_last_12_months,3,0,3,0,4
type_of_credit_accounts,Auto,Auto,Auto,Student,Mortgage
current_balance_of_credit_accounts,12377,1430,16049,4938,10459
total_credit_limit,6149,18922,1197,13206,4011
total_credit_utilization,80,33,57,92,50
public_records_and_collections,Judgement,Judgement,Other,Collection,Collection
loan_amount,4641,3592,1955,3652,2544
purpose_of_loan,Car Financing,Other,Other,Home Improvement,Home Improvement
saving_account_balance,3011,16448,6192,7279,7619
approval_status,Rejected,Approved,Rejected,Rejected,Rejected